### ISSUE TITLE
iOS Still require fill username/pass for fb login

### ISSUE THREAD

**Issue by nvcken** [fbsamples/f8app#44]
I have already login fb account. Why open f8 app still prompt text box require fill username/pass.
I see f8app include fbsdk module, so I thought it should be allow login with fb device account.
I am confuse
p/s: I see login scene look likes web view. Is that the reason ?

**Comment by frantic** [comment]
Haven't seen this issue before. Are you running the code from this repo without any changes (including server side)?

If the app asks you to re-login every time, that might be due to a problem with the token you receive. Use [Facebook Token Debugger](https://developers.facebook.com/tools/debug/) to see what's going on.

**Comment by nvcken** [comment]
I not running the code of this repo. I download f8app from app store
![img_0052](https://cloud.githubusercontent.com/assets/3489866/15309975/e6c86b58-1c15-11e6-8429-7a233620b491.PNG)
