### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by Glavin001** [fbsamples/f8app#47]
I followed the instructions found at http://makeitopen.com/tutorials/building-the-f8-app/local-setup/

![image](https://cloud.githubusercontent.com/assets/1885333/15270281/3076eb30-19f0-11e6-9b2c-bb00b9da2509.png)

- Mac OS 10.11.4
- Node v5.9.0 and v6.0.0 tested
- npm version 3.7.3
- cocoapod 1.0.0
- react-native-cli: 0.1.10
- react-native: 0.23.1

And `npm start` is running and not logging any problems.
It did say:
> Server is now running in development mode on http://localhost:8080

And I noticed the port was `8081` in the iOS app, so I changed https://github.com/fbsamples/f8app/blob/b5df451259897d1838933f01ad4596784325c2ad/ios/F8v2/AppDelegate.m#L44 which did not help.

**Comment by frantic** [comment]
Do you have anything else running on port 8081? You can do `lsof -iTCP:8081` from your Terminal. Another thing you could try is changing the URL in the AppDelegate.m to `127.0.0.1` instead of `localhost` – I think I've seen a problem like that somewhere in RN issues before.

If none of these help – please consider using Stack Overflow, this doesn't seem like F8-app-specific issue.

**Comment by Glavin001** [comment]
I'll give that a shot. Thanks for your advice!

**Comment by flexdhana** [comment]
@frantic changing my AppDelegate.m to 127.0.0.1 instead of localhost works for me.. thanks

this is what i changed to:   jsCodeLocation = [NSURL URLWithString:@"http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=true"];
