### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by rahul100885** [fbsamples/f8app#82]
I was trying to run application on Genymotion and/or android emulator, everything works fine till step 5 mentioned in setup but once I run step 6 I get error "Could not connect to development server" or android emulator and genymotion. 
![device-2016-06-29-191948](https://cloud.githubusercontent.com/assets/208253/16454636/1a8edbc6-3e2f-11e6-8288-1e8ddc1e8318.png)

In case of android emulator IP is 10.0.2.2:8081. 
I know 10.0.3.2 ( In case of genymotion ) and 10.0.2.2 ( In case of emulator ), both connects to local development machine. 
But in step 4 mentioned in setup start server on port 8080 on local machine, which is accessible in browser. 

Is it we have to run some server on port 8081 on local development machine? Or either setup doc missed any steps?

**Comment by nirzari18** [comment]
Make sure npm server is running in background.
If not sure then, after step 5, change terminal window.

If you still face issue then try,
'react-native start'

**Comment by rahul100885** [comment]
@nirzari18 npm start is running in separate tab and starts server on port 8080. 
As you mentioned above I have ran the the above command 'react-native start' which started server on port 8081. Which now get accessed by app but then now following error is coming.

![device-2016-06-30-103507](https://cloud.githubusercontent.com/assets/208253/16477342/747d0278-3eae-11e6-89fa-5eed2d358061.png)

**Comment by nirzari18** [comment]
@rahul100885 I assume, it is as mentioned in official documentation Under "TroubleShooting Run" https://facebook.github.io/react-native/docs/getting-started.html#content

Regarding your current problem, I ran into the same issue as I was trying to install this app yesterday.
It is fixed and pushed by a user in https://github.com/fbsamples/f8app/pull/79 but unfortunately the code has not been merged yet.

Fixes you need:
js -> Login -> LoginScreen.js

Add "var StatusBar = require('StatusBar');" after line 31
At line 73, replace StatusBarIOS.setStyle('default') with StatusBar.setBarStyle('default'); since StatusBarIOS is deprecated https://facebook.github.io/react-native/docs/statusbarios.html.

This should fix it for you!

**Comment by rahul100885** [comment]
Hey thanks @nirzari18 it worked. 
Well but now facebook login, makes application crash.

Another thing, I think "react-native start" should be part of setup steps.

**Comment by frantic** [comment]
>  I think "react-native start" should be part of setup steps.

`react-native run-ios` and `react-native run-android` should start the server automatically, that's why this step wasn't included in the setup. I'll see if I can make it clearer
