### ISSUE TITLE
undefined is not a function(evaluating 'StatusBarIOS.setStyle('default')')

### ISSUE THREAD

**Issue by kittBoy** [fbsamples/f8app#85]
undefined is not a function(evaluating 'StatusBarIOS.setStyle('default')')

**Comment by dphov** [comment]
Same

**Comment by naveensingh-daffodil** [comment]
It is fixed and pushed by a user in #79 but unfortunately the code has not been merged yet.
Fixes you need:
js -> Login -> LoginScreen.js
Add "var StatusBar = require('StatusBar');" after line 31
At line 47, replace StatusBarIOS.setStyle('default') with StatusBar.setBarStyle('default'); since StatusBarIOS is deprecated https://facebook.github.io/react-native/docs/statusbarios.html.
This should fix it for you!

**Comment by dphov** [comment]
@naveensingh-daffodil Thanks a lot!

**Comment by kittBoy** [comment]
@naveensingh-daffodil Thanks !

**Comment by tungh** [comment]
react-native run-android

Same here！

undefined is not a function(evaluating 'StatusBarIOS.setStyle('default')')

**Comment by frantic** [comment]
PRs are welcome!
