### ISSUE TITLE
I do not know the require('F8App')

### ISSUE THREAD

**Issue by stephenkingsley** [fbsamples/f8app#9]
In setup.js,  u used `var F8App = require('F8App')`, i don't know why it is right. i think it should be `var F8App = require('./F8App')`

```javascript
// ./js/setup.js
var F8App = require('F8App') // i do not know why node.js do not find in node_module
```

**Comment by xsgkaka** [comment]
我没有开始读代码，但是我在运行 npm start时出了问题，你能帮帮我吗？

**Comment by frantic** [comment]
Besides CommonJS React Native supports non-standard require system backed by [`node-haste`](https://www.npmjs.com/package/node-haste). Look at `F8App.js`, it has `@providesModule F8App`. Now `require('F8App')` is enough from any file in the app, as long the identifier is unique.

The 2016 app was based on the code from 2015's F8 that used node-haste everywhere, that's why you can still see a couple of places where it hasn't been replaced by CommonJS.

**Comment by stephenkingsley** [comment]
@xsgkaka 哪里出了问题？

**Comment by stephenkingsley** [comment]
@frantic thx~

**Comment by xsgkaka** [comment]
npm install时候报错。具体你看一下我的帖子https://github.com/fbsamples/f8app/issues/10
